WIIS-9654

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -85,38 +85,35 @@ jobs:
                 run: docker compose -f docker-compose.yml -f docker-compose-cypress.yml -p wiistock-cypress up cypress
                 continue-on-error: true
 
-            -   name: Check if there are errors in the logs folder and exit if there are
+            -   name: Copy logs, videos, and dev.log from the container
                 run: |
-                    if [ "$(ls -A /var/www/cypress/logs)" ]; then
-                        echo "There are errors in the logs folder"
-                        exit 1
+                    docker cp wiistock_cypress:/var/www/cypress/logs/ cypress_logs
+                    docker cp wiistock_cypress:/var/www/cypress/videos/ cypress_videos
+                    docker cp wiistock_cypress:/var/www/var/log/dev.log dev_log
+
+            -   name: Check and upload Cypress logs
+                run: |
+                    if [ -d "cypress_logs" ] && [ -n "$(ls -A cypress_logs)" ]; then
+                      echo "Cypress logs exist, indicating errors."
+                      exit 1
                     else
-                        echo "There are no errors in the logs folder"
+                      echo "No Cypress logs found."
                     fi
 
-            -   name: Copy the logs from the container to the folder cypress_logs
-                run: docker cp wiistock_cypress:/var/www/cypress/logs/ cypress_logs
-
-            -   name: Put the logs in the artifacts
+            -   name: Upload Cypress logs artifact
                 uses: actions/upload-artifact@v2
                 with:
-                    name: cypress-logs
-                    path: cypress_logs
+                  name: cypress-logs
+                  path: cypress_logs
 
-            -   name: Copy the videos from the container to the folder cypress_videos
-                run: docker cp wiistock_cypress:/var/www/cypress/videos/ cypress_videos
-
-            -   name: Put the videos generated by cypress in the artifacts
+            -   name: Upload Cypress videos artifact
                 uses: actions/upload-artifact@v2
                 with:
-                    name: cypress-videos
-                    path: cypress_videos
+                  name: cypress-videos
+                  path: cypress_videos
 
-            -   name: Copy the dev.log from the container to the folder dev_log
-                run: docker cp wiistock_cypress:/var/www/var/log/dev.log dev_log
-
-            -   name: Put the dev.log file in the artifacts
+            -   name: Upload dev.log artifact
                 uses: actions/upload-artifact@v2
                 with:
-                    name: dev_log
-                    path: dev_log
+                  name: dev-log
+                  path: dev_log
